site_name: Course de Voitures Autonomes Paris Saclay
nav: 
    - Home: index.md
    - RÃ¨glement: Reglement_CourseVoituresAutonomes.md
    - Voiture type: voiture_type.md
    - About: about.md
theme: readthedocs
site_url: https://ajuton-ens.github.io/CourseVoituresAutonomesSaclay/
site_dir: public

